export enum HrCaseNoteCategory {
  POSITIVE_FEEDBACK = 'POSITIVE_FEEDBACK',
  COMPLAINT = 'COMPLAINT',
  INVESTIGATION = 'INVESTIGATION',
  DISCIPLINARY = 'DISCIPLINARY',
  GRIEVANCE = 'GRIEVANCE',
  RETURN_TO_WORK = 'RETURN_TO_WORK',
  SICKNESS = 'SICKNESS',
  CONDUCT = 'CONDUCT',
  SAFEGUARDING = 'SAFEGUARDING',
}
